var mongoose = require('mongoose');
var Schema    = mongoose.Schema;
var config = require('../../../config')

var LiveLogsMonthReportSchema = new Schema({
  user_id:{type:Number},             
  create_at: { type: Date, default: Date.now },
  platform: { type: String },     //平台
  anchor_group: { type: String },    
  host_manager: {type: String},
  loginname: {type: String},
  host_manager_name: {type: String},
  sum_count: {type: Number, default: 0},    //该日记录条数
  zone: {type: String},
  date: {type: Date},
  year: {type: Number},
  month: {type: Number},
  sum_live_times: {type: Number, default: 0},  //每月开播时长
  sum_revence: {type: Number, default: 0},
  sum_UV: {type: Number, default: 0},
  DAU: {type: Number, default: 0},
  sum_follow_count: {type: Number, default: 0},
  sum_gift_count:{type: Number, default: 0},
  admin_remark: {type:String},
  regist_time: {type:Date},
  key:{type: String},
  location: {type: String},
  gift_revenue_history: { type: Number, default:0},        //历史礼物总收入
  fans: { type: Number, default: 0 },           //粉丝人数

  //每日开播时长
  day_live_times_1:{type:Number, default: 0},
  day_live_times_2:{type:Number, default: 0},
  day_live_times_3:{type:Number, default: 0},
  day_live_times_4:{type:Number, default: 0},
  day_live_times_5:{type:Number, default: 0},
  day_live_times_6:{type:Number, default: 0},
  day_live_times_7:{type:Number, default: 0},
  day_live_times_8:{type:Number, default: 0},
  day_live_times_9:{type:Number, default: 0},
  day_live_times_10:{type:Number, default: 0},
  day_live_times_11:{type:Number, default: 0},
  day_live_times_12:{type:Number, default: 0},
  day_live_times_13:{type:Number, default: 0},
  day_live_times_14:{type:Number, default: 0},
  day_live_times_15:{type:Number, default: 0},
  day_live_times_16:{type:Number, default: 0},
  day_live_times_17:{type:Number, default: 0},
  day_live_times_18:{type:Number, default: 0},
  day_live_times_19:{type:Number, default: 0},
  day_live_times_20:{type:Number, default: 0},
  day_live_times_21:{type:Number, default: 0},
  day_live_times_22:{type:Number, default: 0},
  day_live_times_23:{type:Number, default: 0},
  day_live_times_24:{type:Number, default: 0},
  day_live_times_25:{type:Number, default: 0},
  day_live_times_26:{type:Number, default: 0},
  day_live_times_27:{type:Number, default: 0},
  day_live_times_28:{type:Number, default: 0},
  day_live_times_29:{type:Number, default: 0},
  day_live_times_30:{type:Number, default: 0},
  day_live_times_31:{type:Number, default: 0},

  //每日收入
  day_revence_1:{type:Number, default: 0},
  day_revence_2:{type:Number, default: 0},
  day_revence_3:{type:Number, default: 0},
  day_revence_4:{type:Number, default: 0},
  day_revence_5:{type:Number, default: 0},
  day_revence_6:{type:Number, default: 0},
  day_revence_7:{type:Number, default: 0},
  day_revence_8:{type:Number, default: 0},
  day_revence_9:{type:Number, default: 0},
  day_revence_10:{type:Number, default: 0},
  day_revence_11:{type:Number, default: 0},
  day_revence_12:{type:Number, default: 0},
  day_revence_13:{type:Number, default: 0},
  day_revence_14:{type:Number, default: 0},
  day_revence_15:{type:Number, default: 0},
  day_revence_16:{type:Number, default: 0},
  day_revence_17:{type:Number, default: 0},
  day_revence_18:{type:Number, default: 0},
  day_revence_19:{type:Number, default: 0},
  day_revence_20:{type:Number, default: 0},
  day_revence_21:{type:Number, default: 0},
  day_revence_22:{type:Number, default: 0},
  day_revence_23:{type:Number, default: 0},
  day_revence_24:{type:Number, default: 0},
  day_revence_25:{type:Number, default: 0},
  day_revence_26:{type:Number, default: 0},
  day_revence_27:{type:Number, default: 0},
  day_revence_28:{type:Number, default: 0},
  day_revence_29:{type:Number, default: 0},
  day_revence_30:{type:Number, default: 0},
  day_revence_31:{type:Number, default: 0},

  //每日UV
  day_UV_1:{type:Number, default: 0},
  day_UV_2:{type:Number, default: 0},
  day_UV_3:{type:Number, default: 0},
  day_UV_4:{type:Number, default: 0},
  day_UV_5:{type:Number, default: 0},
  day_UV_6:{type:Number, default: 0},
  day_UV_7:{type:Number, default: 0},
  day_UV_8:{type:Number, default: 0},
  day_UV_9:{type:Number, default: 0},
  day_UV_10:{type:Number, default: 0},
  day_UV_11:{type:Number, default: 0},
  day_UV_12:{type:Number, default: 0},
  day_UV_13:{type:Number, default: 0},
  day_UV_14:{type:Number, default: 0},
  day_UV_15:{type:Number, default: 0},
  day_UV_16:{type:Number, default: 0},
  day_UV_17:{type:Number, default: 0},
  day_UV_18:{type:Number, default: 0},
  day_UV_19:{type:Number, default: 0},
  day_UV_20:{type:Number, default: 0},
  day_UV_21:{type:Number, default: 0},
  day_UV_22:{type:Number, default: 0},
  day_UV_23:{type:Number, default: 0},
  day_UV_24:{type:Number, default: 0},
  day_UV_25:{type:Number, default: 0},
  day_UV_26:{type:Number, default: 0},
  day_UV_27:{type:Number, default: 0},
  day_UV_28:{type:Number, default: 0},
  day_UV_29:{type:Number, default: 0},
  day_UV_30:{type:Number, default: 0},
  day_UV_31:{type:Number, default: 0},

  //每日关注数
  day_follow_count_1:{type:Number, default: 0},
  day_follow_count_2:{type:Number, default: 0},
  day_follow_count_3:{type:Number, default: 0},
  day_follow_count_4:{type:Number, default: 0},
  day_follow_count_5:{type:Number, default: 0},
  day_follow_count_6:{type:Number, default: 0},
  day_follow_count_7:{type:Number, default: 0},
  day_follow_count_8:{type:Number, default: 0},
  day_follow_count_9:{type:Number, default: 0},
  day_follow_count_10:{type:Number, default: 0},
  day_follow_count_11:{type:Number, default: 0},
  day_follow_count_12:{type:Number, default: 0},
  day_follow_count_13:{type:Number, default: 0},
  day_follow_count_14:{type:Number, default: 0},
  day_follow_count_15:{type:Number, default: 0},
  day_follow_count_16:{type:Number, default: 0},
  day_follow_count_17:{type:Number, default: 0},
  day_follow_count_18:{type:Number, default: 0},
  day_follow_count_19:{type:Number, default: 0},
  day_follow_count_20:{type:Number, default: 0},
  day_follow_count_21:{type:Number, default: 0},
  day_follow_count_22:{type:Number, default: 0},
  day_follow_count_23:{type:Number, default: 0},
  day_follow_count_24:{type:Number, default: 0},
  day_follow_count_25:{type:Number, default: 0},
  day_follow_count_26:{type:Number, default: 0},
  day_follow_count_27:{type:Number, default: 0},
  day_follow_count_28:{type:Number, default: 0},
  day_follow_count_29:{type:Number, default: 0},
  day_follow_count_30:{type:Number, default: 0},
  day_follow_count_31:{type:Number, default: 0},

  //每日礼物流水
  day_gift_count_1:{type:Number, default: 0},
  day_gift_count_2:{type:Number, default: 0},
  day_gift_count_3:{type:Number, default: 0},
  day_gift_count_4:{type:Number, default: 0},
  day_gift_count_5:{type:Number, default: 0},
  day_gift_count_6:{type:Number, default: 0},
  day_gift_count_7:{type:Number, default: 0},
  day_gift_count_8:{type:Number, default: 0},
  day_gift_count_9:{type:Number, default: 0},
  day_gift_count_10:{type:Number, default: 0},
  day_gift_count_11:{type:Number, default: 0},
  day_gift_count_12:{type:Number, default: 0},
  day_gift_count_13:{type:Number, default: 0},
  day_gift_count_14:{type:Number, default: 0},
  day_gift_count_15:{type:Number, default: 0},
  day_gift_count_16:{type:Number, default: 0},
  day_gift_count_17:{type:Number, default: 0},
  day_gift_count_18:{type:Number, default: 0},
  day_gift_count_19:{type:Number, default: 0},
  day_gift_count_20:{type:Number, default: 0},
  day_gift_count_21:{type:Number, default: 0},
  day_gift_count_22:{type:Number, default: 0},
  day_gift_count_23:{type:Number, default: 0},
  day_gift_count_24:{type:Number, default: 0},
  day_gift_count_25:{type:Number, default: 0},
  day_gift_count_26:{type:Number, default: 0},
  day_gift_count_27:{type:Number, default: 0},
  day_gift_count_28:{type:Number, default: 0},
  day_gift_count_29:{type:Number, default: 0},
  day_gift_count_30:{type:Number, default: 0},
  day_gift_count_31:{type:Number, default: 0}
})
LiveLogsMonthReportSchema.index({date: -1})
LiveLogsMonthReportSchema.index({key: -1})
LiveLogsMonthReportSchema.index({date: -1,ueser_id: -1})
LiveLogsMonthReportSchema.index({date: -1,platform: -1})
LiveLogsMonthReportSchema.index({date: -1,anchor_group: -1})
LiveLogsMonthReportSchema.index({date: -1,host_manager: -1})
LiveLogsMonthReportSchema.index({platform:-1,ueser_id:-1,year:-1,month:-1})

mongoose.model('Live_Logs_Month_Report',LiveLogsMonthReportSchema)